rb_DB_HOST: 172.17.128.1
rb_DB_PORT: 5432
rb_DB_USER: reblog
rb_DB_PASSWORD: reblog
rb_DB_NAME: reblog
rb_DB_MAXCONN: 1
rb_DB_MINCONN: 1
rb_DB_CONN_LIFETIME: 60
rb_DB_CONN_IDLETIME: 60

rb_API_PORT: 8080

rb_APP_HASHING_COST: 8

rb_APP_JWT_SECRET: 