version: "3"

volumes:
    postgresdata:
        driver: local

services:
    postgres:
        image: postgres:${POSTGRES_TAG}
        ports:
            - "5432:5432"
        env_file:
            - compose.env
        volumes:
            - postgresdata:/var/lib/postgresql/data
        restart: unless-stopped
